List<String> testQuestionsAR = [
  'تشخيص أولي مبني على الذكاء  اﻹصطناعي لقياس مدى قابلية طفلك للأصابة بالتوحد و من ثم اتخذ القرار المناسب',
  ' هل ينظر إليك طفلك عندم تنادية باسمه ؟',
  'هل سهل عليك التواصل بصرياً مع طفلك ؟',
  ' هل يميل طفلك ﻹستخدام اﻹشارة بدل الكلام ؟',
  ' هل يميل طفلك لمشاركة إهتماماته معك؟',
  ' هل يتفاعل طفلك مع ألعابة كأنها تستجيب له ؟',
  'هل يميل طفلك لتخلف أثناء الذهاب إلى مكان ما ؟',
  'إذا كنت أو شخص آخر في العائلة منزعجًا بشكل واضح، فهل تظهر على طفلك علامات عاطفية كإحتضان الشخص الغاضب لتهدئت الوضع؟',
  ' هل كلمات الطفل اﻷولى كانت واضحة ؟',
  'هل يستخدم طفلك الإيماءات البسيطة؟ (على سبيل المثال التلويح بالوداع)',
  'هل يحدق طفلك في لا شيء دون أي غرض واضح؟',
  'ما هو تاريخ الميلاد ؟',
  'ما هو جنس طفلك ؟',
  ' هل يعاني طفلك من اليرق صعوبة النوم ؟',
  ' هل هناك أي فرد من العائلة لديه تاريخ مرضي مع إضطراب طيف التوحد ؟',
  ' ما هو عرق طفلك ؟',
];

List<String> testQuestionsEN = [
  'An initial AI-based diagnosis to measure your child\'s susceptibility to autism, and then take the appropriate decision.',
  'Does your child look at you when you call their name?',
  'Is it easy for you to make eye contact with your child?',
  'Does your child tend to use gestures instead of words?',
  'Does your child tend to share their interests with you?',
  'Does your child interact with their toys as if they are responding to them?',
  'Does your child tend to lag behind when going somewhere?',
  'If you or another family member is visibly upset, does your child show emotional signs like hugging the upset person to calm them down?',
  'Were your child\'s first words clear?',
  'Does your child use simple gestures? (e.g., waving goodbye)',
  'Does your child stare at nothing without any clear purpose?',
  'What is the birth date?',
  'What is your child\'s gender?',
  'Does your child have difficulty sleeping?',
  'Is there any family member with a history of Autism Spectrum Disorder?',
  'What is your child\'s ethnicity?',
];